#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
FILENAME=$(basename "$BASH_SOURCE")
brown='\e[0;33m'
reset='\033[0m'
FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

if [ $# -eq 4 ]; then
	scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$PATH"/"$FILE" "$USERNAME"@"$IP":/home/"$USERNAME"/
else
	echo -e "Usage: ${brown}$FILENAME PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
fi
