#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME"@"$IP":~/ || { echo "Failed to transfer file"; exit 1; }

echo "File transferred successfully"
exit 0
