#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend bg1.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 496909-web-01 54.237.107.190:80
        server 496909-web-02 34.204.76.21:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
