#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.

file="/etc/passwd"

if [ -e "$file" ]; then
    while IFS=: read -r username x uid gid gecos home shell; do
        echo "$username:$uid:$home"
    done < "$file"
else
    echo "File $file does not exist."
fi
