#!/usr/bin/env bash
# Tell the story of passwd

file="/etc/passwd"

if [ -e "$file" ]; then
    while read -r line; do
        username="${line%%:*}"
        uid="${line%%:*}"; uid="${uid#*:}"
        gid="${line%%:*}"; gid="${gid#*:}"
        home="${line%%:*}"; home="${home#*:}"
        shell="${line##*:}"

        passcode="${line%%:*}"; passcode="${passcode##*:}"
        user_info="${line##*:}"

        echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $user_info"
    done < "$file"
else
    echo "File $file does not exist."
fi
